# app/repositories/base.py
from typing import Protocol, Optional, Dict, Any, List

class LinkRepository(Protocol):
    def init_schema(self) -> None: ...
    def create(self, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_by_code(self, code: str) -> Optional[Dict[str, Any]]: ...
    def get_by_id(self, link_id: int) -> Optional[Dict[str, Any]]: ...
    def list(self, limit: int = 100, offset: int = 0) -> List[Dict[str, Any]]: ...
    def update(self, link_id: int, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete(self, link_id: int) -> None: ...
